/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas;

import Controladores.ClientesData;
import Controladores.DetalleVentaData;
import Controladores.ProductoData;
import Controladores.VentaData;
import Modelo.Cliente;
import Modelo.Detalle_Venta;
import Modelo.Producto;
import javax.swing.table.DefaultTableModel;
import Modelo.Venta;
import java.sql.Date;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author giuli
 */
public class VistasVentas extends javax.swing.JInternalFrame {

    private DefaultTableModel modeloTabla;
    private ArrayList<Venta> ventas = new ArrayList();
    private ArrayList<Cliente> clientes = new ArrayList();
    private ArrayList<Producto> productos = new ArrayList();
    private ArrayList<Detalle_Venta> detalleventas = new ArrayList();
    private ClientesData clientD = new ClientesData();
    private ProductoData prodData = new ProductoData();
    private DetalleVentaData dvd = new DetalleVentaData();
    private VentaData ventaD = new VentaData();
    private int id;

    /**
     * Creates new form VistasVenta
     */
    public VistasVentas() {
        initComponents();
        clientes = clientD.listarClientes();
        productos = prodData.listarProductos();
        modeloTabla = new DefaultTableModel();
        encabezado();
        llenarTabla();
        llenarComboBoxClientes();
        llenarComboBoxProductos();
        jCBoxClientes.setSelectedItem(null);
        jCBoxProducto.setSelectedItem(null);
        habilitarBuscar();
                
    }
    private void habilitarBuscar(){
    if(jIdVenta.getText().length()==0){
        btnBuscarC.setEnabled(false);
    }
    else{
        btnBuscarC.setEnabled(true);
        }
    }
    private void llenarComboBoxClientes() {
        for (Cliente c : clientes) {
            jCBoxClientes.addItem(c);
        }
    }

    private void llenarComboBoxProductos() {
        for (Producto p : productos) {
            jCBoxProducto.addItem(p);
        }
    }

    private void encabezado() {
        ArrayList<Object> columna = new ArrayList();
        columna.add("Código");
        columna.add("Fecha");
        columna.add("Cliente");
        columna.add("Producto");
        columna.add("Precio");
        columna.add("Cantidad");
        columna.add("Estado");
        for (Object c : columna) {
            modeloTabla.addColumn(c);
        }
        jTablaVentas.setModel(modeloTabla);
    }

    private void llenarTabla() {
        borrarFilas();
        detalleventas = dvd.listarDetalleVentas();
        for (Detalle_Venta v : detalleventas) {
            modeloTabla.addRow(new Object[]{v.getIdDetalleVenta(), Date.valueOf(v.getVenta().getFecha()), v.getVenta().getCliente().getIdCliente(), v.getProducto().getIdProducto(), v.getPrecioVenta(), v.getCantidad(), v.isEstado()});
        }
    }

    private void borrarFilas() {
        int fila = modeloTabla.getRowCount() - 1;
        for (int i = fila; i >= 0; i--) {
            modeloTabla.removeRow(i);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JLabel();
        jIdVenta = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnEditar = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnBuscarC = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablaVentas = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jDCFecha = new com.toedter.calendar.JDateChooser();
        jRadioEstadoV = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jCantidad = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPrecio1 = new javax.swing.JTextField();
        jCBoxClientes = new javax.swing.JComboBox<>();
        jCBoxProducto = new javax.swing.JComboBox<>();
        btnEliminar = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JLabel();
        btnSalir2 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(820, 440));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel3.setText("Ventas");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 0, -1, -1));

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconos/guardarico.png"))); // NOI18N
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 344, -1, -1));

        jIdVenta.setBackground(new java.awt.Color(0, 102, 153));
        jIdVenta.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        jIdVenta.setForeground(new java.awt.Color(255, 255, 255));
        jIdVenta.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jIdVentaComponentAdded(evt);
            }
        });
        jIdVenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jIdVentaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jIdVentaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jIdVentaKeyTyped(evt);
            }
        });
        getContentPane().add(jIdVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 145, -1));

        jLabel6.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel6.setText("ID Venta:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 39, -1, -1));

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconos/icocrear.png"))); // NOI18N
        btnEditar.setToolTipText("");
        btnEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarMouseClicked(evt);
            }
        });
        getContentPane().add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 343, 50, -1));

        jLabel4.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel4.setText("ID Cliente:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 76, -1, -1));

        btnBuscarC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconos/buscarico.png"))); // NOI18N
        btnBuscarC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarCMouseClicked(evt);
            }
        });
        getContentPane().add(btnBuscarC, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 39, 40, -1));

        jTablaVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTablaVentas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 50, 412, 242));

        jLabel5.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel5.setText("Fecha:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 121, -1, -1));

        jDCFecha.setBackground(new java.awt.Color(0, 102, 153));
        getContentPane().add(jDCFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 121, 152, -1));

        jRadioEstadoV.setBackground(new java.awt.Color(255, 255, 255));
        jRadioEstadoV.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jRadioEstadoV.setText("Estado");
        jRadioEstadoV.setEnabled(false);
        jRadioEstadoV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioEstadoVActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioEstadoV, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 298, 133, -1));

        jLabel7.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel7.setText("ID Producto:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 171, -1, -1));

        jLabel8.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel8.setText("Precio:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 213, -1, -1));

        jCantidad.setBackground(new java.awt.Color(0, 102, 153));
        jCantidad.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        jCantidad.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 264, 160, -1));

        jLabel9.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel9.setText("Cantidad:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 263, -1, -1));

        jPrecio1.setBackground(new java.awt.Color(0, 102, 153));
        jPrecio1.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        jPrecio1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPrecio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 214, 160, -1));

        jCBoxClientes.setBackground(new java.awt.Color(0, 102, 153));
        jCBoxClientes.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        jCBoxClientes.setForeground(new java.awt.Color(255, 255, 255));
        jCBoxClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBoxClientesActionPerformed(evt);
            }
        });
        getContentPane().add(jCBoxClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 77, 152, -1));

        jCBoxProducto.setBackground(new java.awt.Color(0, 102, 153));
        jCBoxProducto.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        jCBoxProducto.setForeground(new java.awt.Color(255, 255, 255));
        jCBoxProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBoxProductoActionPerformed(evt);
            }
        });
        getContentPane().add(jCBoxProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 172, 160, -1));

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconos/eliminarico.png"))); // NOI18N
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 343, -1, -1));

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconos/limpiar.png"))); // NOI18N
        btnLimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimpiarMouseClicked(evt);
            }
        });
        getContentPane().add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 343, -1, -1));

        btnSalir2.setBackground(new java.awt.Color(0, 102, 153));
        btnSalir2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconos/salir.png"))); // NOI18N
        btnSalir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalir2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 330, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioEstadoVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioEstadoVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioEstadoVActionPerformed

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked
        // TODO add your handling code here:
        try {
            java.util.Date fecha = jDCFecha.getDate();
            LocalDate fecVent = fecha.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            Cliente c = (Cliente) jCBoxClientes.getSelectedItem();
            Venta vent = new Venta(fecVent, c);
            Producto p = (Producto) jCBoxProducto.getSelectedItem();
            float precio = Float.parseFloat(jPrecio1.getText());
            int cant = Integer.parseInt(jCantidad.getText());
            Detalle_Venta detaV = new Detalle_Venta(cant, precio, p);
            ventaD.realizarVenta(vent, detaV);
            limpiar();
            llenarTabla();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Datos incorrectos" + e);
        }

    }//GEN-LAST:event_btnGuardarMouseClicked

    private void jCBoxClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBoxClientesActionPerformed

    }//GEN-LAST:event_jCBoxClientesActionPerformed

    private void jCBoxProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBoxProductoActionPerformed

    }//GEN-LAST:event_jCBoxProductoActionPerformed

    private void btnEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseClicked
        // TODO add your handling code here:
        try {
            if (Integer.parseInt(jIdVenta.getText()) != id) {
                JOptionPane.showMessageDialog(null, "Error al modificar venta: No se puede cambiar el ID");
            } else {
                int id = Integer.parseInt(jIdVenta.getText());
                Cliente c = (Cliente) jCBoxClientes.getSelectedItem();
                java.util.Date fecha = jDCFecha.getDate();
                LocalDate fecVent = fecha.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
                Venta vent = new Venta(id, fecVent, c);
                Producto p = (Producto) jCBoxProducto.getSelectedItem();
                float precio = Float.parseFloat(jPrecio1.getText());
                int cant = Integer.parseInt(jCantidad.getText());
                Detalle_Venta detaV = new Detalle_Venta(id, cant, precio, vent, p);
                ventaD.modificarVenta(vent, detaV);
                limpiar();
                llenarTabla();
            }
            llenarTabla();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Datos incorrectos" + e);
        }
    }//GEN-LAST:event_btnEditarMouseClicked

    private void btnBuscarCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarCMouseClicked
        // TODO add your handling code here:
        try {
           if(btnBuscarC.isEnabled()){ 
            Venta venta1 = new Venta();
            id = Integer.parseInt(jIdVenta.getText());
            Detalle_Venta dv = dvd.buscarDetalleVenta(id);
            venta1 = ventaD.buscarVenta(id);
            jCBoxClientes.setSelectedIndex(venta1.getCliente().getIdCliente()-1);//No funciona
            jDCFecha.setDate(Date.valueOf(venta1.getFecha()));
            jCBoxProducto.setSelectedIndex(dv.getProducto().getIdProducto()-1);//No funciona
            jPrecio1.setText(Float.toString(dv.getPrecioVenta()));
            jCantidad.setText(Integer.toString(dv.getCantidad()));
            if (venta1.isEstado()) {
                jRadioEstadoV.setSelected(true);
            } else {
                jRadioEstadoV.setSelected(false);
            }
           }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Datos incorrectos" + e);
        }
    }//GEN-LAST:event_btnBuscarCMouseClicked

    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
        // TODO add your handling code here:
        try {
            if (Integer.parseInt(jIdVenta.getText()) != id) {
                JOptionPane.showMessageDialog(null, "Error");
            } else {
                int id = Integer.parseInt(jIdVenta.getText());
                Cliente c = (Cliente) jCBoxClientes.getSelectedItem();
                java.util.Date fecha = jDCFecha.getDate();
                LocalDate fecVent = fecha.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
                Venta vent = new Venta(id, fecVent, c);
                Producto p = (Producto) jCBoxProducto.getSelectedItem();
                float precio = Float.parseFloat(jPrecio1.getText());
                int cant = Integer.parseInt(jCantidad.getText());
                Detalle_Venta detaV = new Detalle_Venta(id, cant, precio, vent, p);
                ventaD.eliminarVenta(vent, detaV);
                limpiar();
                llenarTabla();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Datos incorrectos" + e);
        }
    }//GEN-LAST:event_btnEliminarMouseClicked

    private void btnLimpiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarMouseClicked
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_btnLimpiarMouseClicked

    private void jIdVentaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jIdVentaKeyPressed
       // TODO add your handling code here:
    }//GEN-LAST:event_jIdVentaKeyPressed

    private void jIdVentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jIdVentaKeyTyped
       // TODO add your handling code here:
    }//GEN-LAST:event_jIdVentaKeyTyped

    private void jIdVentaComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jIdVentaComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jIdVentaComponentAdded

    private void jIdVentaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jIdVentaKeyReleased
       habilitarBuscar(); // TODO add your handling code here:
    }//GEN-LAST:event_jIdVentaKeyReleased

    private void btnSalir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir2ActionPerformed
       dispose();
    }//GEN-LAST:event_btnSalir2ActionPerformed
    private void limpiar() {
        jIdVenta.setText("");
        jDCFecha.setDate(null);
        jPrecio1.setText("");
        jCantidad.setText("");
        jCBoxClientes.setSelectedItem(null);
        jCBoxProducto.setSelectedItem(null);
        habilitarBuscar();
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBuscarC;
    private javax.swing.JLabel btnEditar;
    private javax.swing.JLabel btnEliminar;
    private javax.swing.JLabel btnGuardar;
    private javax.swing.JLabel btnLimpiar;
    private javax.swing.JButton btnSalir2;
    private javax.swing.JComboBox<Cliente> jCBoxClientes;
    private javax.swing.JComboBox<Producto> jCBoxProducto;
    private javax.swing.JTextField jCantidad;
    private com.toedter.calendar.JDateChooser jDCFecha;
    private javax.swing.JTextField jIdVenta;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jPrecio1;
    private javax.swing.JRadioButton jRadioEstadoV;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablaVentas;
    // End of variables declaration//GEN-END:variables
}
