/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas;

import Controladores.CompraData;
import Controladores.DetalleCompraData;
import Controladores.ProductoData;
import Controladores.ProveedorData;
import Modelo.Compra;
import Modelo.DetalleCompra;
import Modelo.Producto;
import Modelo.Proveedor;
import java.sql.Date;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author giuli
 */
public class VistasCompras extends javax.swing.JInternalFrame {
    private DefaultTableModel modeloTabla;
    private ArrayList<Producto> productos = new ArrayList();
    private ArrayList<Proveedor> proveedores = new ArrayList();
    private ArrayList<DetalleCompra> detallecompras = new ArrayList();
    private ProveedorData provD = new ProveedorData();
    private ProductoData prodData = new ProductoData();
    private DetalleCompraData dcd = new DetalleCompraData();
    private CompraData compraD = new CompraData();
    private int id;
    /**
     * Creates new form VistasCompra
     */
    public VistasCompras() {
        initComponents();
        proveedores = provD.listarProveedores();
        productos = prodData.listarProductos();
        modeloTabla = new DefaultTableModel();
        encabezado();
        llenarTabla();
        llenarComboBoxClientes();
        llenarComboBoxProductos();
        jCBoxProveedores.setSelectedItem(null);
        jCBoxProducto.setSelectedItem(null);
        habilitarBuscar();
    }
    private void habilitarBuscar(){
    if(jIdCompra.getText().length()==0){
        btnBuscarC.setEnabled(false);
    }
    else{
        btnBuscarC.setEnabled(true);
        }
    
    }
    private void llenarComboBoxClientes() {
        for (Proveedor p: proveedores) {
            jCBoxProveedores.addItem(p);
        }
    }

    private void llenarComboBoxProductos() {
        for (Producto p : productos) {
            jCBoxProducto.addItem(p);
        }
    }
    private void encabezado() {
        ArrayList<Object> columna = new ArrayList();
        columna.add("Código");
        columna.add("Fecha");
        columna.add("Proveedor");
        columna.add("Producto");
        columna.add("Precio");
        columna.add("Cantidad");
        for (Object c : columna) {
            modeloTabla.addColumn(c);
        }
        jTablaCompras.setModel(modeloTabla);
    }

    private void llenarTabla() {
        borrarFilas();
        detallecompras = dcd.listarDetalleCompras();
        for (DetalleCompra c: detallecompras) {
            modeloTabla.addRow(new Object[]{c.getIdDetalle(), Date.valueOf(c.getCompra().getFecha()), c.getCompra().getProveedor().getIdProveedor(), c.getProducto().getIdProducto(), c.getPrecioCosto(), c.getCantidad()});
        }
    }

    private void borrarFilas() {
        int fila = modeloTabla.getRowCount() - 1;
        for (int i = fila; i >= 0; i--) {
            modeloTabla.removeRow(i);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBuscarC = new javax.swing.JLabel();
        jDCFecha = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablaCompras = new javax.swing.JTable();
        jIdCompra = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jCBoxProveedores = new javax.swing.JComboBox<>();
        jCBoxProducto = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPrecio = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jCantidad = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JLabel();
        btnSalir1 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(820, 440));

        btnBuscarC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconos/buscarico.png"))); // NOI18N
        btnBuscarC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarCMouseClicked(evt);
            }
        });

        jDCFecha.setBackground(new java.awt.Color(0, 102, 153));

        jLabel3.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel3.setText("Compras");

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconos/guardarico.png"))); // NOI18N
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
        });

        jTablaCompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTablaCompras);

        jIdCompra.setBackground(new java.awt.Color(0, 102, 153));
        jIdCompra.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        jIdCompra.setForeground(new java.awt.Color(255, 255, 255));
        jIdCompra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jIdCompraKeyReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel6.setText("ID Compra:");

        jLabel5.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel5.setText("Fecha:");

        jLabel4.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel4.setText("ID Proveedor:");

        jCBoxProveedores.setBackground(new java.awt.Color(0, 102, 153));
        jCBoxProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBoxProveedoresActionPerformed(evt);
            }
        });

        jCBoxProducto.setBackground(new java.awt.Color(0, 102, 153));
        jCBoxProducto.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        jCBoxProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBoxProductoActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel7.setText("ID Producto:");

        jLabel8.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel8.setText("Precio:");

        jPrecio.setBackground(new java.awt.Color(0, 102, 153));
        jPrecio.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        jPrecio.setForeground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel9.setText("Cantidad:");

        jCantidad.setBackground(new java.awt.Color(0, 102, 153));
        jCantidad.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        jCantidad.setForeground(new java.awt.Color(255, 255, 255));

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconos/limpiar.png"))); // NOI18N
        btnLimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimpiarMouseClicked(evt);
            }
        });

        btnSalir1.setBackground(new java.awt.Color(0, 102, 153));
        btnSalir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconos/salir.png"))); // NOI18N
        btnSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalir1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel4))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(56, 56, 56)
                            .addComponent(jLabel5)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnGuardar)
                                .addGap(85, 85, 85)
                                .addComponent(btnLimpiar))
                            .addComponent(jCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalir1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jCBoxProducto, 0, 160, Short.MAX_VALUE)
                                .addComponent(jPrecio)
                                .addComponent(jDCFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCBoxProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBuscarC)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(66, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(313, 313, 313)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jIdCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jIdCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnBuscarC)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(jCBoxProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jDCFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jCBoxProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGuardar)
                            .addComponent(btnLimpiar))
                        .addContainerGap(31, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(26, 26, 26)
                        .addComponent(btnSalir1)
                        .addGap(39, 39, 39))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCBoxProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBoxProveedoresActionPerformed

    }//GEN-LAST:event_jCBoxProveedoresActionPerformed

    private void jCBoxProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBoxProductoActionPerformed

    }//GEN-LAST:event_jCBoxProductoActionPerformed

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked
        // TODO add your handling code here:
        try {
            
            java.util.Date fecha = jDCFecha.getDate();
            LocalDate fecComp = fecha.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            Proveedor prov = (Proveedor) jCBoxProveedores.getSelectedItem();
            Compra comp = new Compra( prov,fecComp);
            Producto p = (Producto) jCBoxProducto.getSelectedItem();
            float precio = Float.parseFloat(jPrecio.getText());
            int cant = Integer.parseInt(jCantidad.getText());
            DetalleCompra detaC = new DetalleCompra(cant, precio,comp,p);
            compraD.realizarCompra(comp, detaC);
            limpiar();
            llenarTabla();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Datos incorrectos" + e);
        }
    }//GEN-LAST:event_btnGuardarMouseClicked

    private void btnBuscarCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarCMouseClicked
        // TODO add your handling code here:
        try {
            if(btnBuscarC.isEnabled()){
            Compra compra1 = new Compra();
            id = Integer.parseInt(jIdCompra.getText());
            DetalleCompra dc = dcd.buscarDetalleCompra(id);
            compra1 = compraD.buscarCompra(id);
            jCBoxProveedores.setSelectedIndex(compra1.getProveedor().getIdProveedor()-1);//No funciona
            jDCFecha.setDate(Date.valueOf(compra1.getFecha()));
            jCBoxProducto.setSelectedIndex(dc.getProducto().getIdProducto()-1);//No funciona
            jPrecio.setText(Float.toString(dc.getPrecioCosto()));
            jCantidad.setText(Integer.toString(dc.getCantidad()));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Datos incorrectos" + e);
        }
    }//GEN-LAST:event_btnBuscarCMouseClicked

    private void btnLimpiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarMouseClicked
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_btnLimpiarMouseClicked

    private void jIdCompraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jIdCompraKeyReleased
      habilitarBuscar();  // TODO add your handling code here:
    }//GEN-LAST:event_jIdCompraKeyReleased

    private void btnSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir1ActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalir1ActionPerformed
    public void limpiar(){
        jIdCompra.setText("");
        jDCFecha.setDate(null);
        jPrecio.setText("");
        jCantidad.setText("");
        jCBoxProveedores.setSelectedItem(null);
        jCBoxProducto.setSelectedItem(null);
        habilitarBuscar();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBuscarC;
    private javax.swing.JLabel btnGuardar;
    private javax.swing.JLabel btnLimpiar;
    private javax.swing.JButton btnSalir1;
    private javax.swing.JComboBox<Producto> jCBoxProducto;
    private javax.swing.JComboBox<Proveedor> jCBoxProveedores;
    private javax.swing.JTextField jCantidad;
    private com.toedter.calendar.JDateChooser jDCFecha;
    private javax.swing.JTextField jIdCompra;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jPrecio;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablaCompras;
    // End of variables declaration//GEN-END:variables
}
